spring:
  config:
    import:
      env.yml
      ,s3.yml
      ,kakaoPay.yml
      ,tossPay.yml
      ,jwt.yml
      ,excel.yml

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true